### ISSUE TITLE
Secret key base confusion with a new Rails app

### ISSUE THREAD

**Issue by jensljungblad** [heroku/heroku-buildpack-ruby#1143] opened 2021-03-24 15:36 UTC
Noticed some confusing behavior deploying a new Rails app to Heroku.

In a new Rails app, you have an encrypted credentials file that by default contains a `secret_key_base`. This will be picked up by `Rails.application.secret_key_base`, as long as no environment variable overrides it. 

It seems like this buildpack actually generates its own secret key base, and sets `SECRET_KEY_BASE`. Meaning if you call `Rails.application.secret_key_base` you will get the value generated by Heroku rather than the value generated by Rails.

Is this documented somewhere? I know Heroku recommends against using encrypted credentials, but I couldn't find anything about this issue.

**Comment by schneems** [comment] 2021-03-24 19:06
Good observation. We've not documented anywhere that we set a default for SECRET_KEY_BASE.

It is semi-documented on my work on porting over this library to fully support cloud native buildpacks on the README https://github.com/heroku/heroku-buildpack-ruby-experimental.

The short version is this:

- If you set your own SECRET_KEY_BASE, we do nothing.
- If you do not set a SECRET_KEY_BASE we generate and set one for you.
- We recommend using our `heroku config` interface for storing secrets rather than using the encrypted file storage that ships with rails.
- If you want to use encrypted file storage locally with rails you could copy our secret key base `heroku run echo $SECRET_KEY_BASE` or you can set your own value manually locally and then again via `heroku config`.

One possibly confusing thing to point out is that we set SECRET_KEY_BASE using the `.profile.d/ruby.sh` script rather than as a config var. This is due to a limitation of the Buildpack v2 specification. You can see the value by running `heroku run bash` and then inspecting the environment with `echo` or `env` commands.

**Comment by jensljungblad** [comment] 2021-03-25 19:51
Nice to see it being documented in the new buildpack 👍 

> We recommend using our heroku config interface for storing secrets rather than using the encrypted file storage that ships with rails.

Yeah I know. The app I'm working on is unfortunately using encrypted credentials which caused some confusion around this. Does this mean that for new Rails 6 apps, you still think it makes sense for the buildpack to specify `SECRET_KEY_BASE`? I know it made sense in the past when a Rails secret file basically looked like:

```yml
production
  secret_key_base: ENV.fetch("SECRET_KEY_BASE")
```

Then it's very clear that the value should be defined in the environment. Now that the default has changed to actually have a value defined in the encrypted credentials, what makes sense for the buildpack?

We ended up removing `secret_key_base` from our encrypted credentials and specified it manually via `heroku config`, so we at least have control over the value.

**Comment by schneems** [comment] 2021-03-31 20:38
> you still think it makes sense for the buildpack to specify SECRET_KEY_BASE?

Honestly. I'm not totally sure. Generally, once we start providing something, it's hard to take it away as it becomes assumed. People will rely on it being there and us it in sometimes surprising ways. In addition to this unknown-unknown case we need to handle new apps and existing apps that have been upgraded that still have a secrets.yml or might be using the `SECRET_KEY_BASE`. For instance, my app CodeTriage has been upgraded through the years and it doesn't have this set but still works because `SECRET_KEY_BASE` env var is present (https://github.com/codetriage/CodeTriage/tree/main/config)

In general, my guidance around the secret key stores has always been...not to use it. Similar to what I mentioned previously. Though I've never gone the next step of actually documenting that stance. It's not a topic I've seen really (m)any support tickets or discussion around since it came out. I'm open to revisit guidance around how we want to approach support. Perhaps there's a way we can warn or error on certain scenarios for example. 

I hear that this was confusing and frustrating and I'm interested in possibly exploring ways to mitigate it in the future with better messaging. Unfortunately without significant effort, I don't think we would be able to stop setting this value.

Also for those following along this post goes into some of the finer points of the transition from secrets.yml to the current encrypted store you may find helpful/interesting https://www.codewithjason.com/understanding-rails-secrets-credentials/

**Comment by andrelaszlo** [comment] 2021-04-01 10:59
My initial thought was that it should be considered a bug since it makes it impossible to use the encrypted credentials file to set the `secret_key_base`, which is the recommended way to store the secret according to the Rails docs:

> For most applications, the correct place to store it is in the encrypted credentials file.

https://api.rubyonrails.org/classes/Rails/Application.html#method-i-secret_key_base

We could however just name the variable something else and override `secret_key_base` in an initializer if the variable is present - so it's not a huge issue. I guess the main issue was understanding where the value was coming from, since it wasn't in the config vars.

**Comment by schneems** [comment] 2021-04-01 14:55
> For most applications, the correct place to store it is in the encrypted credentials file.

In a traditional deploy the flow to deploy something like this would be to SSH onto the machine, either copy or generate the secret key and then git ignore any credential files locally. On Heroku the files you deploy need to be checked into Git.  

Also traditional rails deployments don't have access to a secure config var storage, but Heroku does. That's one of the reasons Rails and Heroku are so divergent on this opinion.

We don't recommend checking secrets into git or storing secrets in files, even if they're encrypted. From our point of view, the feature in Rails isn't really needed and complicates things.

> We could however just name the variable something else and override secret_key_base in an initializer if the variable is present - so it's not a huge issue. I guess the main problem was understanding where the value was coming from, since it wasn't in the config vars.

For more control you can also set the variable `heroku config:set SECRET_KEY_BASE=<yourvaluehere>` and then it will also show up in your `heroku config` output. If you're worried about user sessions getting logged out you could set it to the same current value we've randomly chosen for you. Get it by running `heroku run "env | grep SECRET_KEY_BASE"`.

I would love for this value to show up in the `heroku config` output, but it's a limitation on our v2 buildpack API .

**Comment by schneems** [comment] 2021-04-01 15:27
I wonder if Rails would take a PR that added to those docs "For most applications, the correct place to store it is in the encrypted credentials file. On Heroku this value is set via a SECRET_KEY_BASE environment variable provided by the buildpack."

Traditionally they've resisted adding any vendor specific info into docs as it may become stale and it opens the door to other vendors wanting to add more custom docs.

**Comment by schneems** [comment] 2021-04-12 17:49
I'm going to close this for now

**Closed by schneems** 2021-04-12 17:49 UTC

**Comment by thephw** [comment] 2021-05-06 20:31
@schneems Does setting `SECRET_KEY_BASE` in the buildpack make sense with heroku pipelines? 

Lets say you build an image in a pre-production environment and promote it later to a production environment via pipelines rather than rebuild the image for the new environment. The promoted image will be using `SECRET_KEY_BASE` from the pre-production environment configuration rather than the production environment configuration.

In the case of either the pre-production environment not setting `SECRET_KEY_BASE` or using a generated `SECRET_KEY_BASE` the production environment will get a new random value for each release effectively. This pretty much invalidates all of the session cookies as the signatures will fail. 

I think it may also create some unexpected security behavior in production environments where you'd expect rotating `SECRET_KEY_BASE` in the environment configuration to invalidate all of the sessions. In actuality, this value from the environment is not used with the current behavior.

**Comment by thedarkside** [comment] 2021-11-19 20:21
@schneems this seems to be more weighty than you think. 

We use Gitlabs Auto Deploy pipeline implementation which adopted heroku buildpacks. 

Basically the pipeline builds an image and puts it in the registry. Then the subsequent jobs are testing and deploying the new build image in the configured environments: review, staging, production... on a Kubernetes cluster.

Up until i stumbled upon this issue i thought i can configure different secret_key_bases to all those environments via the ENV vars in the Kubernetes deployments. 

But now i realize that those `SECRET_KEY_BASE` env vars configured for the different deployments in the cluster are being discarded and overridden by the value which is build into the image. 

The issue is that the buildpack allows setting the `SECRET_KEY_BASE` only on buildtime but on runtime it always gets overridden.

So we currently have 2 options: 
- Live with it that all the environments are sharing the same `SECRET_KEY_BASE` from the image
- Build one image for each environment 

Both options are not really satisfactory. 
What we want is to define `SECRET_KEY_BASE` in a deployment env variable in our cluster which then would get used. We dont want to put that in our image.

Seems like many people are misunderstanding this if thats the intended behavior of buildpacks.

**Comment by mattsly** [comment] 2022-02-18 14:28
> * If you do not set a SECRET_KEY_BASE we generate and set one for you.

Does this mean that SECRET_KEY_BASE will change with every deployment then? So that, for example, if you want read an encrypted cookie ("remember me" etc...), that it will be nil as the secret used to write the cookie a few weeks ago might be different than that which is set at read time?

**Comment by thephw** [comment] 2022-02-18 16:44
@mattsly if you promote any image built in a different environment (staging, dev, or preview) then yes, but if it is built in production then maybe. If you build it in production and have the environment variable for `SECRET_KEY_BASE` set it will use that key. If you do not have it set it will change on every deployment.
