### ISSUE TITLE
Error deploying Ruby app on heroku-24

### ISSUE THREAD

**Issue by gaffneyc** [heroku/heroku-buildpack-ruby#1474] opened 2024-06-25 20:38 UTC
Attempted to switch from the `heroku-22` stack to `heroku-24` today but ran into an error that a temp directory couldn't be found. Deploy has been working fine on the `heroku-22` stack. 

**Ruby**: 3.3.3
**Bundler**: 2.5.14
**Rails**: 7.1.3.4

```
remote: -----> Building on the Heroku-24 stack
remote: -----> Using buildpacks:
remote:        1. https://github.com/gaffneyc/heroku-buildpack-jemalloc
remote:        2. https://github.com/deadmanssnitch/heroku-buildpack-dms
remote:        3. heroku/nodejs
remote:        4. heroku/ruby
remote: -----> Performing build in /app since 'build-in-app-dir' is enabled

---- CUT ----

remote: -----> Ruby app detected
remote: system temporary path is world-writable: /tmp
remote: /tmp is world-writable: /tmp
remote: . is world-writable: /app
remote:
remote:  !
remote:  !     could not find a temporary directory
remote:  !
remote: /tmp/tmp.omubV6Vxx8/lib/ruby/3.1.0/tmpdir.rb:39:in `tmpdir': could not find a temporary directory (ArgumentError)
remote:         from /tmp/tmp.omubV6Vxx8/lib/ruby/3.1.0/tmpdir.rb:115:in `tmpdir'
remote:         from /tmp/tmp.omubV6Vxx8/lib/ruby/3.1.0/tmpdir.rb:130:in `create'
remote:         from /tmp/tmp.omubV6Vxx8/lib/ruby/3.1.0/tmpdir.rb:90:in `mktmpdir'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/bundler_wrapper.rb:102:in `initialize'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:28:in `new'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:28:in `bundler'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails7.rb:8:in `use?'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:16:in `block in detect'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:15:in `each'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:15:in `detect'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:15:in `detect'
remote:         from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:16:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
```

**Comment by schneems** [comment] 2024-06-25 22:31
Hello. Thanks for trying out `heroku-24` and thanks for your work with the jemalloc buildpack! Sorry for the build failure. It seems the issue is related to directory permission differences (the warnings suggest that, but I also like to validate what I'm seeing so we're on the same page).

I was able to reproduce the problem by deploying with the ruby-getting-started guide https://gist.github.com/schneems/74a0ee82a50cd80df53fb676d74956da (which worked) and then deploying again after enabling `build-in-app-dir`:

```
$ heroku features:enable build-in-app-dir
Enabling build-in-app-dir for ⬢ secret-headland-17856... done
⛄️ 3.3.1 🚀 /tmp/b36feacd5f7adbb28d1be440ccae538d/ruby-getting-started (main)
$ empty
[main 04da586] empty
⛄️ 3.3.1 🚀 /tmp/b36feacd5f7adbb28d1be440ccae538d/ruby-getting-started (main)
$ git push heroku
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 188 bytes | 188.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Updated 105 paths from 9c08544
remote: Compressing source files... done.
remote: Building source:
remote: Waiting on build...
remote: Waiting on build... (elapsed: 19s)
remote:
remote: -----> Building on the Heroku-24 stack
remote: -----> Using buildpack: heroku/ruby
remote: -----> Performing build in /app since 'build-in-app-dir' is enabled
remote: -----> Ruby app detected
remote: system temporary path is world-writable: /tmp
remote: /tmp is world-writable: /tmp
remote: . is world-writable: /app
remote:
remote:  !
remote:  !     could not find a temporary directory
remote:  !
remote: /tmp/tmp.3rEsQz5JOE/lib/ruby/3.1.0/tmpdir.rb:39:in `tmpdir': could not find a temporary directory (ArgumentError)
remote: 	from /tmp/tmp.3rEsQz5JOE/lib/ruby/3.1.0/tmpdir.rb:115:in `tmpdir'
remote: 	from /tmp/tmp.3rEsQz5JOE/lib/ruby/3.1.0/tmpdir.rb:130:in `create'
remote: 	from /tmp/tmp.3rEsQz5JOE/lib/ruby/3.1.0/tmpdir.rb:90:in `mktmpdir'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/bundler_wrapper.rb:102:in `initialize'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:28:in `new'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:28:in `bundler'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails7.rb:8:in `use?'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:16:in `block in detect'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:15:in `each'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:15:in `detect'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack.rb:15:in `detect'
remote: 	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:16:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
```

We're investigating the issue. 

> Related issue, different app internal ticket link (https://heroku.support/1406806)

The only workarounds I know at this time are to:

- Use `heroku-22`
- Disable that feature

This should be temporary, but I want to let anyone else affected by this issue that they can use one of these temporary workarounds and subscribe to this issue to get a notification once it's fixed and they can go back to `heroku-24` and the `build-in-app-dir` feature.

**Comment by schneems** [comment] 2024-06-25 22:53
A debugging FYI: That warning message from Ruby comes from this commit https://github.com/ruby/ruby/commit/edb5c67195129e1d10f329edb55e486e1874b20e.
 
Not only is it checking if the directory is writeable, but it's also checking if the sticky bit is not set, which from Wikipedia is

>  For directories, when a directory's sticky bit is set, the filesystem treats the files in such directories in a special way so only the file's owner, the directory's owner, or [root user](https://en.wikipedia.org/wiki/Superuser) can rename or delete the file. Without the sticky bit set, any user with write and execute permissions for the directory can rename or delete contained files, regardless of the file's owner. Typically this is set on the /tmp [directory](https://en.wikipedia.org/wiki/Temporary_folder) to prevent ordinary users from deleting or moving other users' files.

Basically, what Ruby is saying is `/tmp` might be insecure, because anyone else on here can read or write your files and they don't know about other isolation steps we have in place (like running builds in containers). Therefore they won't use that directory. When they run out of directories to use, then they throw that error.

We're still tracing down how this is related to the feature.

**Comment by edmorley** [comment] 2024-07-02 08:30
@gaffneyc A fix for this was released yesterday - would you mind giving it another try? :-)

**Comment by andreas-venturini** [comment] 2024-07-02 10:19
@edmorley We encountered the same error earlier, but I can confirm it is working now.

**Comment by edmorley** [comment] 2024-07-03 09:09
@andreas-venturini Thank you for confirming!

**Closed by edmorley** 2024-07-03 09:09 UTC

**Comment by gaffneyc** [comment] 2024-07-03 17:33
Thanks for getting this fixed! I was just able to confirm that it's working for me as well.
