### ISSUE TITLE
Bundle support for version operators in the ruby version

### ISSUE THREAD

**Issue by blackjid** [heroku/heroku-buildpack-ruby#452] opened 2016-01-24 04:07 UTC
The bundler team has merged a PR that let you use version operators for semver in the `ruby` method in the `Gemfile`. This is going to be released in the next version of bundler. https://github.com/bundler/bundler/pull/4064

The thing is that you will be able to add something like this `ruby "~>2.2"` in the Gemfile. How this buildpack is going to handle this case? What ruby version will choose?

thanks

**Comment by schneems** [comment] 2016-01-24 21:57
We will need to see, depending on how it works we still might make you explicitly state a version. 
On one hand getting the latest security patches is good, on the other hand having your site accidentally break because there was a regression and you didn't test locally or even know there was a minor version released is a bad experience. "It worked yesterday and we didn't change anything" is a really bad experience.


---
Richard Schneeman
http://www.schneems.com




On Sat, Jan 23, 2016 at 8:07 PM -0800, "Juan Ignacio Donoso" <notifications@github.com> wrote:












The bundler team has merged a PR that let you use version operators for semver in the ruby method in the Gemfile. This is going to be released in the next version of bundler. bundler/bundler#4064



The thing is that you will be able to add something like this ruby "~>2.2" in the Gemfile. How this buildpack is going to handle this case? What ruby version will choose?



thanks

**Comment by jtarchie** [comment] 2016-01-28 22:38
@schneems, I'm from the Cloud Foundry team that did the original PR for the feature in bundler.

Our use case, as described above, was to allow users to get the latest security patches of Ruby. This feature is great as the Cloud Foundry fork of the buildpack supports only a subset of Ruby versions -- usually the latest two patches of a minor.

It would be awesome if this could be pulled into the code. Our team is willing to help with upstream changes to help you better support this feature.

**Comment by ericboehs** [comment] 2016-05-11 22:31
@schneems Bundler does add an exact version in the `Gemfile.lock`. That'd probably be the correct place to check.

```shell
grep -A1 'RUBY VERSION' Gemfile.lock
```

**Comment by schneems** [comment] 2016-05-11 22:56
I wrote that comment in a taxi on my iphone. Thanks for the sanity check. I also ran locally and confirm it will work with the buildpack.

**Comment by jtarchie** [comment] 2016-05-11 23:35
The `Gemfile.lock` will only contain Ruby version used in development at that time. This means the `ruby` directive in `Gemfile` could specify it is alright with a newer version of Ruby that the buildpack does support.

For example:

`Gemfile` contains:

```
ruby "> 2.2.0"
```

`Gemfile.lock` contains:

```
RUBY VERSION
   2.2.1
```

This is the intended behaviour?

@jvshahid @flavorjones @dannyzen

**Comment by swrobel** [comment] 2017-03-31 01:01
I'm pretty sure this can be closed...

**Comment by flavorjones** [comment] 2017-03-31 02:20
Yes, it can be closed. This went into 1.12.0.pre.1 according to the changelog.

**Closed** 2023-10-06 21:08 UTC
