### ISSUE TITLE
jRuby Could not generate DH key pair

### ISSUE THREAD

**Issue by lephyrius** [heroku/heroku-buildpack-ruby#365] opened 2015-04-23 19:54 UTC
Cannot push app...
I get this error:

```
  Ruby version change detected. Clearing bundler cache.
       Old: jruby 1.7.19 (2.0.0p598) 2015-02-06 fffffff on OpenJDK 64-Bit Server VM 1.8.0_40-cedar14-b25 +jit [linux-amd64]
       New: jruby 1.7.19 (2.0.0p598) 2015-02-06 fffffff on OpenJDK 64-Bit Server VM 1.8.0_40-cedar14-b25 [linux-amd64]
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Picked up JAVA_TOOL_OPTIONS: -Xmx5120m -Djava.rmi.server.useCodebaseOnly=true
       Unfortunately, a fatal error has occurred. Please see the Bundler
       troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
       Handshaker.java:1419:in `checkThrown': java.lang.RuntimeException: Could not generate DH keypair
       from SSLEngineImpl.java:535:in `checkTaskThrown'
       from SSLEngineImpl.java:813:in `readNetRecord'
       from SSLEngineImpl.java:781:in `unwrap'
       from SSLEngine.java:624:in `unwrap'
       from SSLSocket.java:550:in `readAndUnwrap'
       from SSLSocket.java:430:in `doHandshake'
       from SSLSocket.java:203:in `connectCommon'
       from SSLSocket.java:180:in `connect'
       from SSLSocket$INVOKER$i$0$0$connect.gen:-1:in `call'
       from CachingCallSite.java:306:in `cacheAndCall'
       from CachingCallSite.java:136:in `call'
       from CallNoArgNode.java:60:in `interpret'
       from NewlineNode.java:105:in `interpret'
       from ASTInterpreter.java:112:in `INTERPRET_BLOCK'
       from Interpreted19Block.java:206:in `evalBlockBody'
       from Interpreted19Block.java:157:in `yield'
       from Interpreted19Block.java:130:in `yieldSpecific'
       from Block.java:111:in `yieldSpecific'
       from Timeout.java:143:in `timeout'
       from Timeout$INVOKER$s$timeout.gen:-1:in `call'
       from CachingCallSite.java:356:in `cacheAndCall'
       from CachingCallSite.java:213:in `callBlock'
       from CachingCallSite.java:222:in `callIter'
       from CallTwoArgBlockNode.java:62:in `interpret'
       from NewlineNode.java:105:in `interpret'
       from BlockNode.java:71:in `interpret'
       from RescueNode.java:221:in `executeBody'
       from RescueNode.java:116:in `interpret'
       from BeginNode.java:83:in `interpret'
       from NewlineNode.java:105:in `interpret'
       from IfNode.java:116:in `interpret'
       from NewlineNode.java:105:in `interpret'
       from BlockNode.java:71:in `interpret'
       from ASTInterpreter.java:74:in `INTERPRET_METHOD'
       from InterpretedMethod.java:139:in `call'
       from DefaultMethod.java:187:in `call'
       from CachingCallSite.java:306:in `cacheAndCall'
       from CachingCallSite.java:136:in `call'
       from VCallNode.java:88:in `interpret'
       from NewlineNode.java:105:in `interpret'
       from BlockNode.java:71:in `interpret'
       from ASTInterpreter.java:74:in `INTERPRET_METHOD'
       from InterpretedMethod.java:139:in `call'
       from DefaultMethod.java:187:in `call'
       from CachingCallSite.java:306:in `cacheAndCall'
       from CachingCallSite.java:136:in `call'
       from VCallNode.java:88:in `interpret'
       from NewlineNode.java:105:in `interpret'
       from BlockNode.java:71:in `interpret'
       from ASTInterpreter.java:74:in `INTERPRET_METHOD'
       from InterpretedMethod.java:139:in `call'
       from DefaultMethod.java:187:in `call'
```

**Comment by hone** [comment] 2015-07-02 16:15
@jkutner have you ever seen this before?

**Comment by jkutner** [comment] 2015-07-02 16:32
This error usually indicates that the prime size of the certificate key in the SSL handshake is too large. The maximum size that Java "used to" accept was 1024 bits. This was a [pretty well known issue](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6521495) a while back, but my understanding was that it has been fixed in Java 8.

Therefore, I have a suspicion that the `bundle install` may be using the stack JDK (which is JDK 7) instead of the JDK 8 installed for JRuby. I will investigate. 

In the meantime, are you using an unusual Gem sources in your Gemfile? I'm not sure why this would have suddenly started appearing. Another possibility is that the prime size of the certificate key is larger than 2048, which I think is what the limit *should* be.

There is a [JRuby issue](https://github.com/jruby/jruby/issues/2599) that looks like this, but I think they are only mildly related (the older JDK is probably the culprit in both cases).

**Comment by jkutner** [comment] 2015-07-02 16:45
I see the linked issue now. So the server is using 2048 bits:

```sh-session
$ openssl s_client -connect rails-assets.org:443
CONNECTED(00000003)
depth=1 /C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
...
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
...

**Comment by jkutner** [comment] 2015-07-02 17:13
@lephyrius does this still happen for you? I tried to reproduce it with a `Gemfile` like this, but I could not:

```ruby
ruby "1.9.3", engine: "jruby", engine_version: "1.7.20.1"

source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap'
end
```

I think this may have been inadvertently fixed when we overhauled the JVM setup for JRuby apps. But I've not been able to reproduce it in any way to confirm.

**Comment by jkutner** [comment] 2016-05-10 16:24
It turns out this was due to change in cipher by rails-assets.org, which has since been rolled back. For more info see https://github.com/jruby/jruby/issues/2872

**Closed by jkutner** 2016-05-10 16:24 UTC
