### ISSUE TITLE
Setting LD_PRELOAD with jemalloc buildpack results in failures

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-ruby#570] opened 2017-05-22 16:42 UTC
Getting failures with `LD_PRELOAD` using the jemalloc buildpack.

- https://github.com/mojodna/heroku-buildpack-jemalloc.git
- heroku/ruby

```
-----> Using Ruby version: ruby-2.2.6
# ...
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       ERROR: ld.so: object '/app/vendor/jemalloc/lib/libjemalloc.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
       ERROR: ld.so: object '/app/vendor/jemalloc/lib/libjemalloc.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
       ERROR: ld.so: object '/app/vendor/jemalloc/lib/libjemalloc.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
       DEBUG log level not allowed in sandbox mode for security of confidential information. Changing log level to INFO...
       rake aborted!
       JSON::ParserError: 784: unexpected token at 'ERROR: ld.so: object '/app/vendor/jemalloc/lib/libjemalloc.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
       ["ok"]'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:68:in `extract_result'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/uglifier-3.2.0/lib/uglifier.rb:143:in `initialize'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:52:in `new'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:52:in `call'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `yield'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /tmp/build_b3c6ca2da782c34826689eb20be049b8/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
```

Attached internal ticket 475579

**Comment by calebthompson** [comment] 2017-08-07 20:15
https://github.com/mojodna/heroku-buildpack-jemalloc/issues/6 And internal ticket 500069

**Comment by brian-kephart** [comment] 2017-09-16 05:31
I didn't see this before. https://github.com/mojodna/heroku-buildpack-jemalloc/pull/10 fixes this issue but has yet to be merged by a maintainer.

The problem is that the LD_PRELOAD variable in this configuration points to a script that is built by the jemalloc buildpack, so if LD_PRELOAD is called at the beginning the build process, the script and its directory don't exist yet. The issue is solved by exporting LD_PRELOAD to the environment during the script building process, as is done with several other environment variables in that buildpack, so LD_PRELOAD doesn't call assets until they're present.

**Closed** 2023-10-06 21:07 UTC
