### ISSUE TITLE
Error running rake or release tasks `ruby: bad interpreter: No such file or directory`

### ISSUE THREAD

**Issue by joakimk** [heroku/heroku-buildpack-ruby#1005] opened 2020-05-29 08:34 UTC
It works on https://github.com/heroku/heroku-buildpack-ruby.git#v215. The app is soon to be retired, so locking down the deploy stack is fine for us, but this could be an issue for others.

On master we get an error like:
```
remote: -----> Detecting rake tasks        
 
remote:         
 
remote:  !        
 
remote:  !     Could not detect rake tasks        
 
remote:  !     ensure you can run `$ bundle exec rake -P` against your app        
 
remote:  !     and using the production group of your Gemfile.        
 
remote:  !     bash: /tmp/build_FOO/bin/rake: /app/vendor/ruby-2.3.8/bin/ruby: bad interpreter: No such file or directory        
 
remote:  !        
```

**Comment by schneems** [comment] 2020-06-01 17:55
Can you please open a support ticket? Go to help.heroku.com search for "buildpack bug" and open a ticket giving access to your app.

**Comment by schneems** [comment] 2020-06-03 00:50
Did you manage to open a ticket so I can debug this?

-- 
Richard Schneeman
https://www.schneems.com
he/him

**Comment by mmrobins** [comment] 2020-06-03 21:36
@schneems I'm seeing the same issue.  I opened a ticket with an app attached that reproduces the issue https://help.heroku.com/tickets/882725

**Comment by schneems** [comment] 2020-06-04 20:30
It looks like my change doesn't play well with certain versions of Ruby 2.6. I recommend people upgrade to 2.6.6 if they're getting this failure mode:

```
 !     /tmp/build_<dir>/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated bundler 1.17.3, but your Gemfile requires bundler 1.17.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```
@joakimk it looks like your issue is different since you're using an older version of Ruby. Are you able to open a ticket? I would like to investigate your failure mode.

**Comment by schneems** [comment] 2020-06-08 19:21
@joakimk I've merged a fix to my last known regression into master. I'm looking to add some warnings and get a deploy out hopefully in the next week or two. Without more context to reproduce your bug the `heroku/ruby` release might contain the same regression you're seeing. If you have any time this week, can you open a ticket with some more information? Let me know if you have any other questions.

**Comment by wwahammy** [comment] 2020-06-22 20:09
I just wanted to jump in here. I'm also having the exact same error as  @joakimk when trying to deploy to Heroku. using the default buildpack release.

**Comment by michaelarmfield** [comment] 2020-06-22 20:58
Hi all, also wanted to jump in and say that I'm having the exact same error with v216. My app is using Ruby 2.4.9. I can confirm that manually using the v215 works around the issue for now. https://github.com/heroku/heroku-buildpack-ruby.git#v215

**Comment by schneems** [comment] 2020-06-22 20:58
If you've got a failing case I need to be able to reproduce the problem before I can fix it. Please open a ticket help.heroku.com search for "ruby 2.3.8 regression" and give me application access so I can diagnose what's going on. 

I've deployed the code on master branch. I do not recommend pinning to a specific release for too long.

**Comment by schneems** [comment] 2020-06-22 22:24
I see several thumbs up from people seeing this issue but I don't have any tickets in my queue to diagnose. If you've got a case that reproduces this please create a ticket. You can post your ticket number back to this thread and i'll take a look ASAP

**Comment by michaelarmfield** [comment] 2020-06-23 01:46
@schneems Thank you for the help. I've submitted a ticket. Here's the link: [https://help.heroku.com/tickets/890369](url)

**Comment by abepetrillo** [comment] 2020-06-23 11:38
We also have a ticket open which you are already commenting on.

**Comment by schneems** [comment] 2020-06-23 14:46
Thanks for the report. I've managed to get a reproduction. I've rolled back the changes on the buildpack. I'll be investigating this regression. I'll update this issue when I've found the cause(s).

**Comment by schneems** [comment] 2020-06-23 15:06
For internal tracking here are private tickets linked to this issue:


* https://heroku.support/890403
* https://heroku.support/890443
* https://heroku.support/890513
* https://heroku.support/890525
* https://heroku.support/890562
* https://heroku.support/890552
* https://heroku.support/890516
* https://heroku.support/890295
* https://heroku.support/890313
* https://heroku.support/890311
* https://heroku.support/890369
* https://heroku.support/890388

**Comment by schneems** [comment] 2020-06-23 15:58
I think this is the problem:

```
~ $ cat bin/rake | head -n 1
#!/app/vendor/ruby-2.4.9/bin/ruby
```

While that would work in runtime, it fails at build time because there's a different path structure.

This should be:

```
#! /usr/bin/env ruby
```

Commonalities between the apps: They're using an older Rubygems version and they don't have binstubs. It turns out that we're generating this binstub when we're running:

```ruby
        bundle_command = "#{bundle_bin} install --without #{bundle_without} --path #{bundle_path} --binstubs #{bundler_binstubs_path}"
```

This wasn't previously a problem because the binstubs were not first on the path.

Here's an article with some more information: https://devcenter.heroku.com/articles/bad-ruby-binstub-shebang.

It looks like this binstub is generated by Rubygems:

```
##
  # Generates a #! line for +bin_file_name+'s wrapper copying arguments if
  # necessary.
  #
  # If the :custom_shebang config is set, then it is used as a template
  # for how to create the shebang used for to run a gem's executables.
  #
  # The template supports 4 expansions:
  #
  #  $env    the path to the unix env utility
  #  $ruby   the path to the currently running ruby interpreter
  #  $exec   the path to the gem's executable
  #  $name   the name of the gem the executable is for
  #

  def shebang(bin_file_name)
    ruby_name = RbConfig::CONFIG['ruby_install_name'] if @env_shebang
    path = File.join gem_dir, spec.bindir, bin_file_name
    first_line = File.open(path, "rb") {|file| file.gets}

    if /\A#!/ =~ first_line then
      # Preserve extra words on shebang line, like "-w".  Thanks RPA.
      shebang = first_line.sub(/\A\#!.*?ruby\S*((\s+\S+)+)/, "#!#{Gem.ruby}")
      opts = $1
      shebang.strip! # Avoid nasty ^M issues.
    end

    if which = Gem.configuration[:custom_shebang]
      # replace bin_file_name with "ruby" to avoid endless loops
      which = which.gsub(/ #{bin_file_name}$/," #{RbConfig::CONFIG['ruby_install_name']}")

      which = which.gsub(/\$(\w+)/) do
        case $1
        when "env"
          @env_path ||= ENV_PATHS.find {|env_path| File.executable? env_path }
        when "ruby"
          "#{Gem.ruby}#{opts}"
        when "exec"
          bin_file_name
        when "name"
          spec.name
        end
      end

      "#!#{which}"
    elsif not ruby_name then
      "#!#{Gem.ruby}#{opts}"
    elsif opts then
      "#!/bin/sh\n'exec' #{ruby_name.dump} '-x' \"$0\" \"$@\"\n#{shebang}"
    else
      # Create a plain shebang line.
      @env_path ||= ENV_PATHS.find {|env_path| File.executable? env_path }
      "#!#{@env_path} #{ruby_name}"
    end
  end
```

I'm looking into if the Ruby buildpack can configure rubygems to generate the correct binstub. But this needs to work across all rubygems versions.

**Comment by schneems** [comment] 2020-06-23 16:58
This looks like a compilation problem:

```
$ cd ~/Downloads/ruby-2.3.8
$ ls bin
erb	gem	irb	rake	rdoc	ri	ruby
$ cat bin/rake | head -n 1
#!/app/vendor/ruby-2.3.8/bin/ruby
```

When we compiled Ruby 2.3.8 that shebang line was generated in there. I cannot tell bundler or rubygems to not add the shebang line since it's not happening at build time, it's already happened.

It looks like this behavior was fixed in more recent versions of Ruby. Here's 2.7.1:

```
Running cat bin/rake on ⬢ quiet-mountain-45252... up, run.9658 (Free)
#!/bin/sh
```

I see two options for fixing this:

### Recompile all older rubies

It's probably possible to configure how that shebang line gets generated at build time. We could recompile and re-upload all binaries that have this problem.

- Pros: It would fix the problem
- Cons: Replacing existing binaries is risky, it might trigger other bugs. It's not something I feel comfortable doing en-masse

A variant of this: We could edit the existing binaries to fix the shebang lines. I'm equally afraid of this.

### Manually replace Binstub's shebang lines

If I isolate this behavior to a maximum range then when the Ruby buildpack detects that it's deploying an older ruby version it could re-write the shebang line to be `/usr/bin/env ruby` instead of an absolute path.

- Pros: It would fix the problem
- Cons: I might introduce a bug while writing shebang lines. It's less risky than re-compiling binaries though


### Symlink `/app` to the current build dir

At the root of this issue is that build and runtime directories are different. We could fix this by symlinking `/app` to `$(pwd)`. 

- Pros: It would fix the problem. It might actually future-proof us for other discrepancies between build and runtime path issues. 
- Cons: The change is invasive. It might be invasive in a good way, but it's still invasive. It's unknown how this might affect other buildpacks that are designed to manipulate the path such as the "monorepo" buildpack.

**Comment by schneems** [comment] 2020-06-24 18:25
Looking into the issue more it seems that the problem is limited to Ruby 2.2 and Ruby 2.3 binaries. I'm going to write some tooling to verify this is true. If that's the case then the best solution will be to re-compile which won't require a buildpack change.

**Comment by joakimk** [comment] 2020-06-25 10:03
Sorry I haven't been able to get back on this. It looks like you got a reproduction but tell me if you need mine too.

**Comment by schneems** [comment] 2020-06-30 17:18
## Context

I decided to fix this by re-building binaries and manually replacing the binstubs. You can see the work here:

https://github.com/heroku/docker-heroku-ruby-builder/pull/5

This is the code: https://github.com/heroku/docker-heroku-ruby-builder/blob/e1c5f086db54819eba527257127af4446a61b862/build.rb#L192-L205

I tried to force Ruby to do this from the outside in, but could not find a way to force the behavior. Here's me asking about it on Twitter if you have ideas on how to do this in a more supported less "manual" manner: https://twitter.com/schneems/status/1277975436497055747

## Action

I re-compiled and re-released all the binaries today. 

```
Running: bundle exec rake upload[2.3.0,cedar-14]
Running: bundle exec rake upload[2.3.1,cedar-14]
Running: bundle exec rake upload[2.3.2,cedar-14]
Running: bundle exec rake upload[2.3.3,cedar-14]
Running: bundle exec rake upload[2.3.4,cedar-14]
Running: bundle exec rake upload[2.3.5,cedar-14]
Running: bundle exec rake upload[2.3.6,cedar-14]
Running: bundle exec rake upload[2.3.7,cedar-14]
Running: bundle exec rake upload[2.3.8,cedar-14]
Running: bundle exec rake upload[2.4.0,cedar-14]
Running: bundle exec rake upload[2.4.1,cedar-14]
Running: bundle exec rake upload[2.4.2,cedar-14]
Running: bundle exec rake upload[2.4.3,cedar-14]
Running: bundle exec rake upload[2.4.4,cedar-14]
Running: bundle exec rake upload[2.4.5,cedar-14]
Running: bundle exec rake upload[2.4.6,cedar-14]
Running: bundle exec rake upload[2.4.7,cedar-14]
Running: bundle exec rake upload[2.4.8,cedar-14]
Running: bundle exec rake upload[2.4.9,cedar-14]
Running: bundle exec rake upload[2.3.0,heroku-16]
Running: bundle exec rake upload[2.3.1,heroku-16]
Running: bundle exec rake upload[2.3.2,heroku-16]
Running: bundle exec rake upload[2.3.3,heroku-16]
Running: bundle exec rake upload[2.3.4,heroku-16]
Running: bundle exec rake upload[2.3.5,heroku-16]
Running: bundle exec rake upload[2.3.6,heroku-16]
Running: bundle exec rake upload[2.3.7,heroku-16]
Running: bundle exec rake upload[2.3.8,heroku-16]
Running: bundle exec rake upload[2.4.0,heroku-16]
Running: bundle exec rake upload[2.4.1,heroku-16]
Running: bundle exec rake upload[2.4.2,heroku-16]
Running: bundle exec rake upload[2.4.3,heroku-16]
Running: bundle exec rake upload[2.4.4,heroku-16]
Running: bundle exec rake upload[2.4.5,heroku-16]
Running: bundle exec rake upload[2.4.6,heroku-16]
Running: bundle exec rake upload[2.4.7,heroku-16]
Running: bundle exec rake upload[2.4.8,heroku-16]
Running: bundle exec rake upload[2.4.9,heroku-16]
Running: bundle exec rake upload[2.4.0,heroku-18]
Running: bundle exec rake upload[2.4.1,heroku-18]
Running: bundle exec rake upload[2.4.2,heroku-18]
Running: bundle exec rake upload[2.4.3,heroku-18]
Running: bundle exec rake upload[2.4.4,heroku-18]
Running: bundle exec rake upload[2.4.5,heroku-18]
Running: bundle exec rake upload[2.4.6,heroku-18]
Running: bundle exec rake upload[2.4.7,heroku-18]
Running: bundle exec rake upload[2.4.8,heroku-18]
Running: bundle exec rake upload[2.4.9,heroku-18]
```

## Confirmation

If you're subscribing to this issue because you have an app that broke when I released the buildpack, can you please try the default/main branch of this buildpack along with these recompiled binaries?

You'll need to replace `heroku/ruby` buildpack with `https://github.com/heroku/heroku-buildpack-ruby`. For instance you can see all your buildpacks by running:

```
$ heroku buildpacks
=== issuetriage Buildpack URLs
1. heroku/metrics
2. https://github.com/mojodna/heroku-buildpack-jemalloc.git#v5.0.0
3. heroku/nodejs
4. heroku/ruby
```

Then in this case you could replace `heroku/ruby` by referencing it by index like this:

```
$ heroku buildpacks:set -i 4 https://github.com/heroku/heroku-buildpack-ruby
Buildpack set. Next release on issuetriage will use:
  1. heroku/metrics
  2. https://github.com/mojodna/heroku-buildpack-jemalloc.git#v5.0.0
  3. heroku/nodejs
  4. https://github.com/heroku/heroku-buildpack-ruby
```

Then deploy and make sure it works as expected. If you get an error, but it works with `heroku/ruby` please post back on this thread. I'll also likely going to want access to your app via a support ticket https://help.heroku.com search "ruby: bad interpreter".

**Comment by schneems** [comment] 2020-06-30 22:21
It looks like there's still bugs to work out:

```
~ $ rake -P
rake assets:precompile
~ $ bundle exec rake -P
bundler: failed to load command: rake (/app/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
```

I believe this is because `bundle exec` messes with the rubygems path and the file `bin/rake` is generated by rubygems at compile time and is not aware of bundler. I've not investigated fully though.

**Comment by schneems** [comment] 2020-07-01 16:14
I want to walk back that last comment. The failure seems to be based on a problem with my test in https://github.com/heroku/heroku-buildpack-ruby/pull/1026 where it was not pulling in the latest changes from github (which included `rake` as a gem in the Gemfile). It looks like everything is working as intended. I did miss Ruby 2.4.9. So I am re-compiling and pushing that later today. Other than that it looks like this primary issue is fixed. 

There is another issue that came out of v216 which is being discussed on https://github.com/heroku/heroku-buildpack-ruby/issues/1025. But I believe it is distinctly different from this one.

Here's the instructions for testing out my fix:

If you're subscribing to this issue because you have an app that broke when I released the buildpack, can you please try the default/main branch of this buildpack along with these recompiled binaries?

You'll need to replace `heroku/ruby` buildpack with `https://github.com/heroku/heroku-buildpack-ruby`. For instance you can see all your buildpacks by running:

```
$ heroku buildpacks
=== issuetriage Buildpack URLs
1. heroku/metrics
2. https://github.com/mojodna/heroku-buildpack-jemalloc.git#v5.0.0
3. heroku/nodejs
4. heroku/ruby
```

Then in this case you could replace `heroku/ruby` by referencing it by index like this:

```
$ heroku buildpacks:set -i 4 https://github.com/heroku/heroku-buildpack-ruby
Buildpack set. Next release on issuetriage will use:
  1. heroku/metrics
  2. https://github.com/mojodna/heroku-buildpack-jemalloc.git#v5.0.0
  3. heroku/nodejs
  4. https://github.com/heroku/heroku-buildpack-ruby
```

Then deploy and make sure it works as expected. If you get an error, but it works with `heroku/ruby` please post back on this thread. I'll also likely going to want access to your app via a support ticket https://help.heroku.com search "ruby: bad interpreter".

**Comment by schneems** [comment] 2020-07-06 14:50
I've recompiled 2.4.10 for all stacks and deployed them. No binary versions should have this problem.

**Closed** 2020-07-07 14:36 UTC

**Comment by wwahammy** [comment] 2020-07-13 20:12
Does this mean we can go back to `heroku/ruby` for our ruby buildpack?

**Comment by schneems** [comment] 2020-07-15 16:23
> Does this mean we can go back to heroku/ruby for our ruby buildpack?

Correct. I've rolled this out on Monday and I've not gotten a single support ticke about it. Everything looks stable.

**Comment by sachins1812** [comment] 2020-07-24 06:52
@schneems Sorry to say but Again I am facing the same problem deploying my project.

https://help.heroku.com/tickets/902689

**Comment by schneems** [comment] 2020-07-24 14:29
I replied to the ticket. For anyone in the future that has what they believe to be the issue here please try deploying with v217:

```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby#v217
```

Then deploy. If it passes but `heroku/ruby` fails on the exact same code then it's worth investigation. 

To date all issues that have been opened as a result of this deploy turned out to be previously undiscovered bugs in customer applications, for example, code that set the `BUNDLE_GEMFILE` to the wrong location, but it was previously being booted in a way that the code wasn't being run.

As a minor point if the output does not include `ruby: bad interpreter: No such file or directory` then this specific issue isn't happening. You may be seeing https://github.com/heroku/heroku-buildpack-ruby/issues/1025 which relates more to bundler and code loading. To my knowlege no one should be getting a `ruby: bad interpreter: No such file or directory` error. I've not seen a ticket with one since I deployed v218.
