### ISSUE TITLE
heroku_detecting_active_storage_config running in non-prod env?

### ISSUE THREAD

**Issue by JPrevost** [heroku/heroku-buildpack-ruby#744] opened 2018-04-23 19:02 UTC
Hi. A recent change to this build pack seems to be causing problems with my builds.

```
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/shell_helpers.rb:69:in `block in run!': Command: 'bin/rails runner "puts %Q{heroku_detecting_active_storage_config=#{Rails.application.config.active_storage.service}}"' failed unexpectedly: (StandardError)
/tmp/build_045b058d3f7f940c0fb27fbc961b7d60/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/rubygems_integration.rb:377:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? sqlite3 is not part of the bundle. Add it to your Gemfile. (Gem::LoadError)
```

I suspect, but haven't confirmed, that the command is running without specifying to run in the production environment and my app uses sqlite for dev/test.

https://github.com/heroku/heroku-buildpack-ruby/blob/7697f5905704f2ef7c16fae25d70ae64680efcba/lib/language_pack/rails5.rb#L53

**Comment by JPrevost** [comment] 2018-04-23 19:51
Similar environment related issues were reported in the referenced Pull Request discussion by others.

**Comment by K1N5L4Y3R** [comment] 2018-04-23 20:25
As of today I have a similar issue when trying to deploy.

**NOTE**: There are no changes in our codebase that have to do with encrypted secrets or ActiveStorage. We were using encrypted secrets just fine last week.

```
remote: sh: 2: Syntax error: Unterminated quoted string
remote:  !
remote:  !     Command: 'bin/rails runner "puts %Q{heroku_detecting_active_storage_config=#{Rails.application.config.active_storage.service}}"' failed unexpectedly:
remote:  !     /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:62:in `handle_missing_key': Missing encryption key to decrypt secrets with. Ask your team for your master key and put it in ENV["RAILS_MASTER_KEY"] (Rails::Secrets::MissingKeyError)
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:36:in `key'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:102:in `encryptor'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:44:in `decrypt'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:81:in `preprocess'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:29:in `block in parse'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:26:in `each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:26:in `each_with_object'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/secrets.rb:26:in `parse'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:399:in `secrets'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/config/initializers/rollbar.rb:3:in `block in <top (required)>'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/rollbar-2.15.5/lib/rollbar/notifier.rb:51:in `configure'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/rollbar-2.15.5/lib/rollbar.rb:66:in `configure'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/config/initializers/rollbar.rb:1:in `<top (required)>'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:277:in `load'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:277:in `block in load'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:249:in `load_dependency'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:277:in `load'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/engine.rb:657:in `block in load_config_initializer'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/notifications.rb:170:in `instrument'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/engine.rb:656:in `load_config_initializer'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/engine.rb:613:in `each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/engine.rb:613:in `block in <class:Engine>'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:32:in `run'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:50:in `each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:50:in `tsort_each_child'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `call'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/initializable.rb:60:in `run_initializers'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:361:in `initialize!'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/config/environment.rb:5:in `<top (required)>'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `require'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `block in require'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:249:in `load_dependency'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc2/lib/active_support/dependencies.rb:283:in `require'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/application.rb:337:in `require_environment!'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/commands/runner/runner_command.rb:29:in `perform'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/command/base.rb:65:in `perform'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/command.rb:46:in `invoke'
remote:  !     from /tmp/build_e9c516f33a41748c93527564e4555c97/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'

##
# lines omitted
##

remote:  !     from bin/rails:9:in `require'
remote:  !     from bin/rails:9:in `<main>'
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to app-name
```

Our config/storage.yml looks like this:

```
amazon:
  service: S3
  access_key_id: <%= Rails.application.secrets.aws.try(:[], :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.aws.try(:[], :secret_access_key) %>
  region: <%= Rails.application.secrets.aws.try(:[], :region) %>
  bucket: <%= Rails.application.secrets.aws.try(:[], :bucket) %>
```

**Comment by JPrevost** [comment] 2018-04-23 20:29
Yeah, it feels like it's not using ENV=production before the new check. I'm not 100% confident that is it, but that warning is definitely not worth breaking production builds so it would be great if it was either reverted or fixed. Thoughts @schneems ?

**Comment by schneems** [comment] 2018-04-23 20:44
Sorry about that. Thanks for the update, that's definitely a thing that was missed. I've got a PR #745 

Can someone try to deploy one of these apps with this buildpack:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-ruby#schneems/env-in-check
```

And let me know if the issue persists? Also if it doesn't if you could open a ticket https://help.heroku.com and search "Rails 5.2 cannot deploy". Once you have a ticket number if you paste it here, it will help me debug and I can take a look directly.

I'm working on a rollback patch as well in case that doesn't fix the issue.

**Comment by K1N5L4Y3R** [comment] 2018-04-23 20:48
@schneems I can try to deploy it with that buildpack, just curious if/how we can go back to the regular one after this issue is fixed. Once I know this, I can make the test and come back at you.

BTW I did create a ticket (577735)

**Comment by kylefox** [comment] 2018-04-23 20:59
@schneems Still seeing the error after setting the buildpack:

```
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/shell_helpers.rb:69:in `block in run!': Command: 'bin/rails runner "puts %Q{heroku_detecting_active_storage_config=#{Rails.application.config.active_storage.service}}"' failed unexpectedly: (StandardError)
/tmp/build_937df4ac67f5b481bc9840526e4b3be8/vendor/bundle/ruby/2.5.0/gems/fog-core-1.44.3/lib/fog/core/service.rb:244:in `validate_options': Missing required arguments: aws_access_key_id, aws_secret_access_key (ArgumentError)
```

Is the buildpack making the assumption that ActiveStorage is configured? I noticed that our error message points to `fog/core/service.rb`, whereas other people are seeing different errors:

- @frenkel https://github.com/heroku/heroku-buildpack-ruby/pull/739#issuecomment-383673166 has `aws-sigv4/signer.rb:517:in extract_credentials_provider'`
- @dinatih https://github.com/heroku/heroku-buildpack-ruby/pull/739#issuecomment-383693104 has `config/environments/production.rb:52:in +': no implicit conversion of nil into String (TypeError)`

**Comment by schneems** [comment] 2018-04-23 21:00
I verified the patch fixes this section, I'm moving forwards with getting it merged and deploying. 

> is the buildpack making the assumption that ActiveStorage is configured?

No, if it's not configured, it should output a `nil` instead of `:local` which should not trigger the warning.

**Comment by kylefox** [comment] 2018-04-23 21:02
Ok, thanks — I probably just did something wrong setting the buildpack 😅

**Closed** 2018-04-23 21:04 UTC

**Comment by schneems** [comment] 2018-04-23 21:08
> Ok, thanks — I probably just did something wrong setting the buildpack

I haven't quite deployed just yet. I'll post again once I do. The issue is that my check wasn't using the user's environment variables, only the ones we set on the buildpack manually. So if you have any env vars that are used at initialization time like configuring error trackers, or storage, etc. it will error.

**Comment by JPrevost** [comment] 2018-04-23 21:26
Seems good @schneems thx! 🍻

**Comment by kylefox** [comment] 2018-04-23 21:29
>> Ok, thanks — I probably just did something wrong setting the buildpack

> I haven't quite deployed just yet. I'll post again once I do.

Sorry, should've clarified — it wasn't working after setting the custom `buildpacks:set` as you described.

But it seems to be working now, _without_ a custom buildpack. Thanks for the fix 👍

**Comment by unsafeact** [comment] 2018-04-24 14:34
Sorry, I'm a total newbie to rails/heroku, and I'm fundamentally lost since I also see these errors! Would really appreciate if someone could point me to what I need to do to. Thanks a lot and apologies if this is not the right place to ask!

Small part of the log:
`
remote: sh: 1: Syntax error: "(" unexpected
remote:  !
remote:  !     Command: 'bin/rails runner "puts %Q{heroku_detecting_active_storage_config=#{Rails.application.config.try(:active_storage).try(:service)}}"' failed unexpectedly:
remote:  !     /tmp/build_a4a7335bd9f305efb19dc1cec23809b5/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_one_attached' for #<Class:0x0000000003d5ab08> (NoMethodError)
remote:  !     from /tmp/build_a4a7335bd9f305efb19dc1cec23809b5/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob/representable.rb:7:in `block in <module:Representable>'`

**Comment by courtsimas** [comment] 2018-04-24 15:42
I'm having the same exact issue (rails 5.2, ruby 2.6 preview), 

```Asset precompilation completed (6.99s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote: sh: 1: Syntax error: "(" unexpected
remote:  !
remote:  !     Command: 'bin/rails runner "puts %Q{heroku_detecting_active_storage_config=#{Rails.application.config.try(:active_storage).try(:service)}}"' failed unexpectedly:
remote:  !     bash: bin/rails: No such file or directory
remote:  !
```

Just tried twice in the last hour.

**Comment by schneems** [comment] 2018-04-24 16:14
I'm going to rollback the requirement that it expects this command to succeed #749

Basically what's happening is people are deploying with a bug and instead of the commands failing in production, they're failing at the build step with an error that is very incomprehensible. The solution is to not fail when this command errors, but instead continue as we would have previously.

> bash: bin/rails: No such file or directory

You should have binstubs. You can get it by running `$ bundle exec rake app:update:bin`. While it might not prevent you from deploying, our systems do expect the `bin/rails` command to exist for Rails 5.2 apps.

**Comment by schneems** [comment] 2018-04-24 16:42
I reverted the logic that required the `rails runner` call to succeed. Your app will still fail in the same place which means you won't get a warning if you accidentally deploy with active storage set to `:local`, but it is better to be able to deploy at all. Here's the PR that was merged and deployed https://github.com/heroku/heroku-buildpack-ruby/pull/749.

Please let me know if that doesn't fix this issue.

**Comment by schneems** [comment] 2018-04-24 17:27
Interesting, the `rails new` should make binstubs for you. Glad you got it working.

**Comment by frenkel** [comment] 2018-04-24 17:52
@schneems #749 fixed the problem for me, thanks!

**Comment by unsafeact** [comment] 2018-04-24 19:36
Great, my deploy was successful, too! Thanks a lot!

**Comment by mindaslab** [comment] 2018-09-01 03:16
I am getting this error now. Wonder what's wrong. Ive switched to build packs mentioned here and still am getting this error.

**Comment by cxsper** [comment] 2018-09-26 21:07
@mindaslab have you figured it out? same problem here. with any buildpacks

**Comment by cxsper** [comment] 2018-09-26 22:06
@mindaslab nvm, I just forgot to run `db:migrate`
